// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-SXtqANvwgRBIprWdaKJrveRrsRzjDws',
    appId: '1:740149629242:web:2199bb5a72126e08530003',
    messagingSenderId: '740149629242',
    projectId: 'kfupm-app-8d53e',
    authDomain: 'kfupm-app-8d53e.firebaseapp.com',
    storageBucket: 'kfupm-app-8d53e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANjWtiYGxz6iekETFy2JTWoJ3r0Wz-DDA',
    appId: '1:740149629242:android:55e6139e3d97f406530003',
    messagingSenderId: '740149629242',
    projectId: 'kfupm-app-8d53e',
    storageBucket: 'kfupm-app-8d53e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ39JaT_h_q4flENkOwXUR5VWv5eMYrXw',
    appId: '1:740149629242:ios:23d5f86f67a6d69e530003',
    messagingSenderId: '740149629242',
    projectId: 'kfupm-app-8d53e',
    storageBucket: 'kfupm-app-8d53e.appspot.com',
    iosBundleId: 'com.example.kfupm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ39JaT_h_q4flENkOwXUR5VWv5eMYrXw',
    appId: '1:740149629242:ios:1b158d14bda92b60530003',
    messagingSenderId: '740149629242',
    projectId: 'kfupm-app-8d53e',
    storageBucket: 'kfupm-app-8d53e.appspot.com',
    iosBundleId: 'com.example.kfupm.RunnerTests',
  );
}
